%JDSY 01-25-2011
%%% Initilazation script for He4 system
close all;
clear all;
instrreset;

global smdata; 
% global smscan;

%Load rack
if 1==1
  %note rack is generated by "He4RackCreationScript"
 load('C:\Users\Steinberg-lab\Documents\Special Measure 2\custom\smdata1.mat');
 instrreset;
end

smaddchannel('Keithley 1','dcv','K1dcv',[],1);
smaddchannel('Keithley 1','dcc','K1dcc',[],2);
smaddchannel('Lockin 2','X','L2X',[],3);
smaddchannel('Keithley 2','dcv','K2dcv',[],4);
smaddchannel('Keithley 2','dcc','K2dcc',[],5);
smaddchannel('Dmm 1','dcv','dmm1dcv',[],6);


%% Intialization Settings

Keithley1Voltage = 1;   %0 for current source (and Tempature), 1 for voltage source (and gating) 
Keithley2Voltage = 1; 

%% GPIB addresses for machines
k1adr = 25;
k2adr = 24;
l2adr = 9;
dmm1adr = 26;

%% Serial addresses for serial machines
dac1adr = 'COM9'; %COM port for the DAC 

%% Ethernet addresses for eithernet machines

%Cryo4G magnet (He3)
ip='132.64.80.17';
port=4444;

%% Retrieve instrument indices and open connection to machines

k1ind = sminstlookup('Keithley 1');
k2ind = sminstlookup('Keithley 2');
dmm1ind = sminstlookup('Dmm 1');
l2ind = sminstlookup('Lockin 2');
dac1ind = sminstlookup('DAC 1');
magind=sminstlookup('Cryo4G');

%create Keithley 1 object
obj = instrfind('Type', 'tcpip', 'RemoteHost', ip, 'RemotePort', port, 'Tag', '');
if isempty(obj)
    obj = tcpip(ip,port);
else
    fclose(obj);
    obj= obj(1);
end
smdata.inst(k1ind).data.inst = gpib('ni', 0, k1adr);

%create Keithley 2 object
smdata.inst(k2ind).data.inst = gpib('ni', 0, k2adr);

%create dmm1 object
smdata.inst(dmm1ind).data.inst = gpib('ni', 0, dmm1adr);

%create lockin 2 object
smdata.inst(l2ind).data.inst = gpib('ni', 0, l2adr);

%create dac 1 object
smdata.inst(dac1ind).data.inst = serial(dac1adr,'BaudRate',115200);

%create Cryo4G magnet object

obj = instrfind('Type', 'tcpip', 'RemoteHost', ip, 'RemotePort', port, 'Tag', '');
if isempty(obj)
    obj = tcpip(ip,port);
else
    fclose(obj);
    obj= obj(1);
end
smdata.inst(magind).data.inst=obj;


fopen(smdata.inst(k1ind).data.inst);
fopen(smdata.inst(k2ind).data.inst);
fopen(smdata.inst(dmm1ind).data.inst);
fopen(smdata.inst(l2ind).data.inst);
fopen(smdata.inst(dac1ind).data.inst);

%% Keithley 2400 is intialized differently as voltage source or for
%%% temperature measurement
if Keithley1Voltage == 1
    %initialize the Keithley 2400 as a voltage source
    fprintf(smdata.inst(k1ind).data.inst,'*RST');
    fprintf(smdata.inst(k1ind).data.inst,':sour:func volt');
    fprintf(smdata.inst(k1ind).data.inst,':sour:volt:mode fix');
    fprintf(smdata.inst(k1ind).data.inst,':sour:volt:rang 0.2');
    %fprintf(smdata.inst(k1ind).data.inst,':sour:volt:rang 10');
    fprintf(smdata.inst(k1ind).data.inst,':sens:curr:prot 1E-6');
    fprintf(smdata.inst(k1ind).data.inst,':sens:curr:RANG 1e-6');
    fprintf(smdata.inst(k1ind).data.inst,':outp on');
else
    %initialize Keithley 2400 as a current source (for reading T or driving
    %magnet)
    fprintf(smdata.inst(k1ind).data.inst,'*RST');
    fprintf(smdata.inst(k1ind).data.inst,':sour:func curr');
    fprintf(smdata.inst(k1ind).data.inst,':sens:func "volt"');
    fprintf(smdata.inst(k1ind).data.inst,':outp on');
    fprintf(smdata.inst(k1ind).data.inst,':sour:curr 1e-5') % for T
%     fprintf(smdata.inst(3).data.inst,':sour:curr 0e-8')   % for current biasing
%     fprintf(smdata.inst(k1ind).data.inst,':sour:curr:RANG 1e-8');
%     fprintf(smdata.inst(k1ind).data.inst,':sens:volt:RANG 200e-2')
end


if Keithley2Voltage == 1
    %initialize the Keithley 2400 as a voltage source
    fprintf(smdata.inst(k2ind).data.inst,'*RST');
    fprintf(smdata.inst(k2ind).data.inst,':sour:func volt');
    fprintf(smdata.inst(k2ind).data.inst,':sour:volt:mode fix');
    fprintf(smdata.inst(k2ind).data.inst,':sour:volt:rang 0.2');
    %fprintf(smdata.inst(k2ind).data.inst,':sour:volt:rang 10');
    fprintf(smdata.inst(k2ind).data.inst,':sens:curr:prot 1E-6');
    fprintf(smdata.inst(k2ind).data.inst,':sens:curr:RANG 1e-6');
    fprintf(smdata.inst(k2ind).data.inst,':outp on');
else
    %initialize Keithley 2400 as a current source (for reading T or driving
    %magnet)
    fprintf(smdata.inst(k2ind).data.inst,'*RST');
    fprintf(smdata.inst(k2ind).data.inst,':sour:func curr');
    fprintf(smdata.inst(k2ind).data.inst,':sens:func "volt"');
    fprintf(smdata.inst(k2ind).data.inst,':outp on');
    fprintf(smdata.inst(k2ind).data.inst,':sour:curr 1e-5') % for T
%     fprintf(smdata.inst(3).data.inst,':sour:curr 0e-8')   % for current biasing
%     fprintf(smdata.inst(k2ind).data.inst,':sour:curr:RANG 1e-8');
%     fprintf(smdata.inst(k2ind).data.inst,':sens:volt:RANG 200e-2')
end


