%JDSY 01-25-2011
%%% Initilazation script for He4 system
close all;
clear all;
instrreset;

global smdata; 
global smscan;

%Load rack
if 1==1
  %note rack is generated by "He4RackCreationScript"
%   load('C:\SpecialMeasure2011\Measurement Setups\He4 Setup\betterrack2.mat');
 load('C:\Documents and Settings\He4\My Documents\Valla\Capacitance_scans\Cap_rack.mat');
%    load('C:\Documents and Settings\He4\My Documents\Hadar\Scans\Vlk1_vlk2_T_vs_Dummy.mat');
%  load('Z:\group\measurements\Ben\20111206_MOS2tunnel\rack_20111206_C.mat');
%   load('Z:\group\measurements\Javier\GM-1-01 09-13-2011\rack09-13-2011v2.mat');
  %load('He4-Rack_01-Feb-2011');
%   load('Z:\group\Topological Insulator\Samples\Exfoliated Bi2Se3 Samples\LE4\He4\LE4_Rack.mat');
%load('Z:\group\Topological Insulator\Samples\Exfoliated Bi2Se3 Samples\Sample HS056\He4\056_Rack.mat');
  instrreset;
end

%% Intialization Settings
UseCryoMag = 1;   %% 1 = use magnet
TwoLockin = 1;    %% 1 = use both lockins
KeithleyVoltage = 0;   %0 for current source (and Tempature), 1 for voltage source (and gating) 

%% GPIB addresses for machines
k2400adr = 15;
k2700adr = 16;

sr830adr = 8;
MagContadr = 1;
Sr830_top_adr = 9;

%% Retrieve instrument indices and open connection to machines
sminstlookup('LowerLockin');
sr830ind = sminstlookup('LowerLockin');
k2400ind = sminstlookup('K2400V');
k2700ind = sminstlookup('DMM');
dacind = sminstlookup('DecaDAC');
k2400indT = sminstlookup('K2400T');
MagContind = sminstlookup('MagnetController');
sr830topind = sminstlookup('UpperLockin');

smdata.inst(sr830ind).data.inst = gpib('ni', 0, sr830adr);
smdata.inst(k2400ind).data.inst = gpib('ni', 0, k2400adr);
smdata.inst(k2700ind).data.inst = gpib('ni', 0, k2700adr);
smdata.inst(dacind).data.inst = serial('COM5');
if UseCryoMag == 1
    smdata.inst(MagContind).data.inst = gpib('ni', 0, MagContadr);
end
if TwoLockin == 1
    smdata.inst(sr830topind).data.inst = gpib('ni', 0, Sr830_top_adr);
end

fopen(smdata.inst(sr830ind).data.inst);
fopen(smdata.inst(k2400ind).data.inst);
fopen(smdata.inst(k2700ind).data.inst);
fopen(smdata.inst(dacind).data.inst);
if UseCryoMag == 1
    fopen(smdata.inst(MagContind).data.inst);
end
if TwoLockin == 1
    fopen(smdata.inst(sr830topind).data.inst);
end

%% Keithley 2400 is intialized differently as voltage source or for
%%% temperature measurement
if KeithleyVoltage == 1
    %initialize the Keithley 2400 as a voltage source
    fprintf(smdata.inst(k2400ind).data.inst,'*RST');
    fprintf(smdata.inst(k2400ind).data.inst,':sour:func volt');
    fprintf(smdata.inst(k2400ind).data.inst,':sour:volt:mode fix');
    fprintf(smdata.inst(k2400ind).data.inst,':sour:volt:rang 0.2');
    %fprintf(smdata.inst(k2400ind).data.inst,':sour:volt:rang 10');
    fprintf(smdata.inst(k2400ind).data.inst,':sens:curr:prot 1E-6');
    fprintf(smdata.inst(k2400ind).data.inst,':sens:curr:RANG 1e-6');
    fprintf(smdata.inst(k2400ind).data.inst,':outp on');
else
    %initialize Keithley 2400 as a current source (for reading T or driving
    %magnet)
    fprintf(smdata.inst(3).data.inst,'*RST');
    fprintf(smdata.inst(3).data.inst,':sour:func curr');
    fprintf(smdata.inst(3).data.inst,':sens:func "volt"');
    fprintf(smdata.inst(3).data.inst,':outp on');
    fprintf(smdata.inst(3).data.inst,':sour:curr 1e-5') % for T
%     fprintf(smdata.inst(3).data.inst,':sour:curr 0e-8')   % for current biasing
%     fprintf(smdata.inst(k2400ind).data.inst,':sour:curr:RANG 1e-8');
%     fprintf(smdata.inst(k2400ind).data.inst,':sens:volt:RANG 200e-2')
end



%% initialize the magnet
if UseCryoMag == 1
    fprintf(smdata.inst(MagContind).data.inst,'UNITS T');
    fprintf(smdata.inst(MagContind).data.inst,'RANGE 0 15');
    fprintf(smdata.inst(MagContind).data.inst,'RATE 0 0.08');
end

if 1==1
    smdata.inst(dacind).data.rng = [-10 10;-10 10;-10 0;-10 0;-10 0;-10 0;-10 0;-10 0;-10 0;-10 0;-10 10;-10 10];
    %initialize the DecaDAC as a DAC voltage source
    DACzero=32768; %measured bit where DAC is zero
    bit_str=sprintf('B0;M2;C1;D%.0f;',DACzero);
    query(smdata.inst(dacind).data.inst,bit_str); %sets DAC to zero
    %reset any ramps
    query(smdata.inst(dacind).data.inst, 'B0;M2;C0;S0;'); 
    query(smdata.inst(dacind).data.inst, 'B0;M2;C0;U65535;');
    query(smdata.inst(dacind).data.inst, 'B0;M2;C0;L0;');
end

LoadSensorCal;
smdata.inst(k2400indT).data.inst = smdata.inst(k2400ind).data.inst;
smgui;

%cd('Z:\group\Topological Insulator\Samples\Thin Film Samples Ferhat\21X1_24X2\');
% cd('Z:\group\Topological Insulator\Samples\Exfoliated Bi2Se3 Samples\LE4\He4\');
% load('C:\Special_Measure\Measurement Setups\He4 Setup\He4 Example Scans\smscan_BG');
% cd('Z:\group\measurements\Javier\GM-1-01 09-19-2011');
cd('Z:\group\Topological Insulator\Samples\Exfoliated Bi2Se3 Samples\Sample LE014\He4\');